### ISSUE TITLE
MINM record/replay for USB Xbox One Controller?

### ISSUE THREAD

**Issue by bentaylordata** [usb-tools/Facedancer#12]
Wasn't sure where to post this. Is this library capable of having a linux machine support a man in the middle between my controller and the xbox where it records all of my actions, but allows the xbox to make and replay its own actions?

**Comment by ktemkin** [comment]
Theoretically, yes -- if you have a FaceDancer device and are willing to write some python (and learn about USB HID), this is very much possible.  :)

This is mostly proxying and injecting HID data, so the Switch controller MITM'ing examples are relevant, here.
