### ISSUE TITLE
Facedancer on a macOS - a lot of timeouts proxying an XBOX one controller

### ISSUE THREAD

**Issue by mrstock** [usb-tools/Facedancer#23]
I'm trying to use facedancer with the GreatFet One card as a MITM between an XBOX One and an XBOX ELITE controller.

I'm using the code as provided on github with the last merge # 22.

I made only **"aesthetic" changes** to make what happens (at least for me) more readable.

### Some premises:

The XBOX One console needs some sort of authentication to communicate with the controller, if authentication does not take place in the early stages of communication, the console stops all communication with the controller. If authentication is successful, the controller is accepted and communications take place correctly until the controller is disconnected.

**I'm doing tests on both Linux and MacOS.**

**On linux it works quite well:**
authentication does not always happen ( I need to understand why not always ), but when it happens, communications continue in a perfect way indefinitely (until I disconnect the controller). So the controller and the console work just as if the controller were directly connected to the XBOX One's USB port ( transparently as it should be ).

**Some screenshots from linux with a correct authentication ( 240 bytes packet length ) :** 

![1](https://user-images.githubusercontent.com/188262/65161151-57a50600-da37-11e9-8aa0-6caf372f7e7d.png)

![2](https://user-images.githubusercontent.com/188262/65161213-76a39800-da37-11e9-949a-6dbac10803b2.png)

![3 auth](https://user-images.githubusercontent.com/188262/65161220-7b684c00-da37-11e9-861e-4bc17696dae1.png)

**On MacOS:**
communications seem to work correctly only up to the interface configuration, then after the first two or three packets, all communications on endpoints 1 ( 0x81 ) go into timeouts ( and aborted ) and the controller is turned off by the console or simply ignored.

**Some screenshots from macOS using the same code producing a timeouts loop**

<img width="1694" alt="mac1" src="https://user-images.githubusercontent.com/188262/65162666-e3b82d00-da39-11e9-830a-6f4502612e8e.png">

<img width="2380" alt="mac2" src="https://user-images.githubusercontent.com/188262/65162795-18c47f80-da3a-11e9-8ade-254c90a61987.png">

The red warning lines are produced by the libusb library enabling the environment variable : 
`LIBUSB_DEBUG = 3`

"my debug" is a change I made to get some other useful information

output of dmesg ring buffer from GreatFET board : 

```
Ring buffer contained 4070 bytes of data:
[   629512890] usb error:transaction reports transaction error! aborting.
[   629527829] usb error:transaction reports transaction error! aborting.
[   629542496] usb error:transaction reports transaction error! aborting.
[   629557969] usb error:transaction reports transaction error! aborting.
[   629573600] usb error:transaction reports transaction error! aborting.
[   629588786] usb error:transaction reports transaction error! aborting.
[   629604263] usb error:transaction reports transaction error! aborting.
[   629619572] usb error:transaction reports transaction error! aborting.
[   629634455] usb error:transaction reports transaction error! aborting.
[   629648476] usb error:transaction reports transaction error! aborting.
[   629662985] usb error:transaction reports transaction error! aborting.
[   629678413] usb error:transaction reports transaction error! aborting.
[   629693250] usb error:transaction reports transaction error! aborting.
[   629707458] usb error:transaction reports transaction error! aborting.
[   629721530] usb error:transaction reports transaction error! aborting.
[   629735958] usb error:transaction reports transaction error! aborting.
[   629750495] usb error:transaction reports transaction error! aborting.
[   629764261] usb error:transaction reports transaction error! aborting.
[   629778739] usb error:transaction reports transaction error! aborting.
[   629793001] usb error:transaction reports transaction error! aborting.
[   629807153] usb error:transaction reports transaction error! aborting.
[   629821123] usb error:transaction reports transaction error! aborting.
[   629835410] usb error:transaction reports transaction error! aborting.
[   629850782] usb error:transaction reports transaction error! aborting.
[   629865759] usb error:transaction reports transaction error! aborting.
[   629880134] usb error:transaction reports transaction error! aborting.
[   629893844] usb error:transaction reports transaction error! aborting.
[   629907865] usb error:transaction reports transaction error! aborting.
[   629922164] usb error:transaction reports transaction error! aborting.
[   629937000] usb error:transaction reports transaction error! aborting.
[   629951815] usb error:transaction reports transaction error! aborting.
[   629966533] usb error:transaction reports transaction error! aborting.
[   629980548] usb error:transaction reports transaction error! aborting.
[   629995301] usb error:transaction reports transaction error! aborting.
[   630010806] usb error:transaction reports transaction error! aborting.
[   630026408] usb error:transaction reports transaction error! aborting.
[   630041817] usb error:transaction reports transaction error! aborting.
[   630056143] usb error:transaction reports transaction error! aborting.
[   630070407] usb error:transaction reports transaction error! aborting.
[   630084097] usb error:transaction reports transaction error! aborting.
[   630097636] usb error:transaction reports transaction error! aborting.
[   630112586] usb error:transaction reports transaction error! aborting.
[   630127954] usb error:transaction reports transaction error! aborting.
[   630143228] usb error:transaction reports transaction error! aborting.
[   630157420] usb error:transaction reports transaction error! aborting.
[   630172405] usb error:transaction reports transaction error! aborting.
[   630188031] usb error:transaction reports transaction error! aborting.
[   630203561] usb error:transaction reports transaction error! aborting.
[   630219037] usb error:transaction reports transaction error! aborting.
[   630234589] usb error:transaction reports transaction error! aborting.
[   630250057] usb error:transaction reports transaction error! aborting.
[   630265404] usb error:transaction reports transaction error! aborting.
[   630280490] usb error:transaction reports transaction error! aborting.
[   630295712] usb error:transaction reports transaction error! aborting.
[   630311026] usb error:transaction reports transaction error! aborting.
```

Output of `libusb -v` : [libusb_controller elite.txt](https://github.com/usb-tools/Facedancer/files/3627005/libusb_controller.elite.txt)

It seems that this proxy is not really transparent and some packages are lost ... I have seen that there are some firmware changes in place to solve multiple 64 bytes packets. Do you think the problem can be linked?

Any suggestions are welcome, thanks !

Stock

**Comment by straithe** [comment]
Are you still experiencing this issue, @mrstock ?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
