### ISSUE TITLE
Dealing with USB descriptor longer than declared length

### ISSUE THREAD

**Issue by HclX** [usb-tools/Facedancer#31]
I'm running into parsing issues with a descriptor blob longer than specification says:

![image](https://user-images.githubusercontent.com/3332879/73564737-0c532900-4415-11ea-9e57-df2f88584419.png)

This is from a USB headset (Plantronics C5220T). The above snapshot is from wireshark capture of the device's CONFIGURATION descriptor. As it shows, the device is reporting a 9-byte endpoint descriptor, rather than a 7-byte according to the USB specification. 

I was trying to parse it using facedancer's USBEndpoint.from_binary_descriptor class and it fails at "struct.unpack" call.

**Comment by ktemkin** [comment]
Sounds like there needs to be a `[0:7]` on the data passed to `struct.unpack`;  or we should use the `wLength` reported in the descriptor itself.

**Comment by HclX** [comment]
The same should apply to all the "USBDescribable" subclasses. If needed, I can make a pull request for this.

**Comment by ktemkin** [comment]
Agreed; and if you'd like to, I'd be happy to test and merge that. :)

Thanks!

**Comment by ktemkin** [comment]
This should have been resolved by https://github.com/usb-tools/Facedancer/pull/32; closing.
