### ISSUE TITLE
Proxying a Joystick Controller

### ISSUE THREAD

**Issue by Colton2017** [usb-tools/Facedancer#46]
Hi, I am having trouble while I am proxying a Flight Joystick controller. I run Facedancer.py and I get the controller to be recognized by both the host and target computer, but that is as far as I get. I am unable to actually play a game or move any controls through the full setup. Any help is appreciated and let me know if I need to provide any additional information.

**Comment by straithe** [comment]
Are you still experiencing this issue, @Colton2017?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
